services:
  - type: web
    name: backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    postDeployCommand: |
      python manage.py makemigrations trips
      python manage.py migrate
