# Generated by Django 5.1.7 on 2025-03-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_logentry_remarks_trip_co_driver_trip_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='current_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='current_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
