# Generated by Django 5.1.7 on 2025-03-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0003_trip_carrier_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="office_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
