# Generated by Django 5.1.7 on 2025-03-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0005_logentry_latitude_logentry_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logentry",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="logentry",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
