# Generated by Django 5.1.7 on 2025-03-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0006_alter_logentry_latitude_alter_logentry_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("Driving", "Driving"),
                    ("On Duty (Not Driving)", "On Duty (Not Driving)"),
                    ("Off Duty", "Off Duty"),
                    ("Sleeper Berth", "Sleeper Berth"),
                ],
                max_length=50,
            ),
        ),
    ]
